### ISSUE TITLE
use_github_actions()

### ISSUE THREAD

**Issue by higgi13425** [EmilHvitfeldt/bookdown-github-actions-netlify#2]
Hi Emil,

I ran into one problem in following your blog post.
I could not (initially) use
`use_github_action("bookdown.yaml")`
It would throw an error, claiming that `use_github_action` was not available.

I read the documents in the development version of `usethis`
and it appears that you have to run 
`use_github_actions()` first,
and then you can run
`use_github_action("bookdown.yaml")`

This seems to work.
I don't know if it is something specific to my setup (session_info below), or a breaking change in the dev version of `usethis`

If this is not just me, it is probably worth updating your blog post.

thanks,
Peter

─ Session info ────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       macOS High Sierra 10.13.6   
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Detroit             
 date     2020-03-21                  

─ Packages ────────────────────────────────────────────────────────────────────────────
 package     * version    date       lib source                        
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                
 backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.0)                
 bookdown      0.18       2020-03-05 [1] CRAN (R 3.6.0)                
 callr         3.4.2      2020-02-12 [1] CRAN (R 3.6.0)                
 cli           2.0.2      2020-02-28 [1] CRAN (R 3.6.0)                
 clipr         0.7.0      2019-07-23 [1] CRAN (R 3.6.0)                
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                
 curl          4.3        2019-12-02 [1] CRAN (R 3.6.1)                
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                
 devtools    * 2.2.2      2020-02-17 [1] CRAN (R 3.6.0)                
 digest        0.6.25     2020-02-23 [1] CRAN (R 3.6.0)                
 ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.1)                
 evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                
 fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.1)                
 fs            1.3.2      2020-03-05 [1] CRAN (R 3.6.0)                
 gh            1.1.0      2020-01-24 [1] CRAN (R 3.6.1)                
 git2r         0.26.1     2019-06-29 [1] CRAN (R 3.6.0)                
 glue          1.3.2      2020-03-12 [1] CRAN (R 3.6.0)                
 htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.0)                
 httr          1.4.1      2019-08-05 [1] CRAN (R 3.6.0)                
 jsonlite      1.6.1      2020-02-02 [1] CRAN (R 3.6.1)                
 knitr         1.28       2020-02-06 [1] CRAN (R 3.6.1)                
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.0)                
 memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                
 packrat       0.5.0      2018-11-14 [1] CRAN (R 3.6.2)                
 pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.1)                
 pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 3.6.1)                
 processx      3.4.2      2020-02-09 [1] CRAN (R 3.6.2)                
 ps            1.3.2      2020-02-13 [1] CRAN (R 3.6.0)                
 R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.1)                
 Rcpp          1.0.4      2020-03-17 [1] CRAN (R 3.6.0)                
 remotes       2.1.1      2020-02-15 [1] CRAN (R 3.6.0)                
 renv          0.9.3      2020-02-10 [1] CRAN (R 3.6.2)                
 rlang         0.4.5      2020-03-01 [1] CRAN (R 3.6.0)                
 rmarkdown     2.1        2020-01-20 [1] CRAN (R 3.6.1)                
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                
 rstudioapi    0.11       2020-02-07 [1] CRAN (R 3.6.0)                
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                
 testthat      2.3.2      2020-03-02 [1] CRAN (R 3.6.0)                
 usethis     * 1.5.1.9000 2020-03-21 [1] Github (r-lib/usethis@2431e97)
 withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                
 xfun          0.12       2020-01-13 [1] CRAN (R 3.6.1)                
 yaml          2.2.1      2020-02-01 [1] CRAN (R 3.6.1)                

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

**Comment by EmilHvitfeldt** [comment]
Thanks for you note, I'll fix the post about it!

**Comment by higgi13425** [comment]
Thanks for the post - very helpful!
