### ISSUE TITLE
workflow not building bookdown

### ISSUE THREAD

**Issue by rainer-rq-koelle** [EmilHvitfeldt/bookdown-github-actions-netlify#3]
Hi Emil, thanks for your blog and detailed description. I followed your recipe, however, the book is not build. I have no real idea what is not working. the netlify deploy messages suggest that the build command is not found (c.f. below: 11:22:08 AM: No build command found, continuing to publishing). However, I cannot tell how to fix this. Thanks for your help.
Rainer

netlify page: https://pru-learnr.netlify.app
github repo: https://github.com/rainer-rq-koelle/pru-LearnR-booklet

netlify deploy log
11:22:04 AM: Build ready to start
11:22:06 AM: build-image version: b0258b965567defc4a2d7e2f2dec2e00c8f73ad6
11:22:06 AM: build-image tag: v3.4.1
11:22:06 AM: buildbot version: 9042ba4998dab698f1f37fb8d36912c08a387191
11:22:06 AM: Fetching cached dependencies
11:22:06 AM: Starting to download cache of 28.3KB
11:22:06 AM: Finished downloading cache in 84.125472ms
11:22:06 AM: Starting to extract cache
11:22:06 AM: Finished extracting cache in 9.375635ms
11:22:06 AM: Finished fetching cache in 93.79427ms
11:22:06 AM: Starting to prepare the repo for build
11:22:07 AM: Preparing Git Reference refs/heads/master
11:22:08 AM: No build command found, continuing to publishing
11:22:08 AM: Starting to deploy site from '/'
11:22:08 AM: Creating deploy tree 
11:22:08 AM: Creating deploy upload records
11:22:08 AM: 1 new files to upload
11:22:08 AM: 0 new functions to upload
11:22:09 AM: Finished processing build request in 2.342891379s
11:22:09 AM: Starting post processing
11:22:09 AM: Post processing - HTML
11:22:09 AM: Post processing - header rules
11:22:09 AM: Post processing - redirect rules
11:22:09 AM: Post processing done
11:22:09 AM: Site is live

**Comment by statkclee** [comment]
+1

**Comment by rainer-rq-koelle** [comment]
I am happy, if you close this. I am now building and deploying the bookdown project by hand. Hoping that I find the time to understand github actions better and/or how to get the pipeline in place. Nonetheless. Thanks for your work, Emil.
